# Generated by Django 5.2.4 on 2025-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=6, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('semester', models.PositiveBigIntegerField()),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=10)),
                ('student_contact', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('student_mail', models.EmailField(max_length=254)),
                ('leave_request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
