# Generated by Django 5.2.4 on 2025-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavesystemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='guardian_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='student_contact',
            field=models.CharField(max_length=20),
        ),
    ]
